#!/bin/sh -eu

initgpio() {
  PIN="${1}"
  INITIAL_VALUE="${2}"
  if [ ! -e "/sys/class/gpio/gpio${PIN}" ]; then
    echo "${PIN}" > /sys/class/gpio/export
    sleep 1
  fi
  echo "out" > "/sys/class/gpio/gpio${PIN}/direction"
  echo "${INITIAL_VALUE}" > "/sys/class/gpio/gpio${PIN}/value"
}

OFF='1'
TRAY_PIN='22'
PLANTS_PIN='24'

initgpio "${TRAY_PIN}" "${OFF}"
initgpio "${PLANTS_PIN}" "${OFF}"
