#!/bin/sh -eu

echo "$(date -uIs) plants on"

ON='0'
OFF='1'

PLANTS_PIN='24'

echo "${ON}" > "/sys/class/gpio/gpio${PLANTS_PIN}/value"

sleep 1800

echo "${OFF}" > "/sys/class/gpio/gpio${PLANTS_PIN}/value"
