#!/bin/sh -eu

echo "$(date -uIs) tray on"

ON='0'
OFF='1'

PLANTS_PIN='24'
echo "${ON}" > "/sys/class/gpio/gpio${PLANTS_PIN}/value"
sleep 1
echo "${OFF}" > "/sys/class/gpio/gpio${PLANTS_PIN}/value"

TRAY_PIN='22'
echo "${ON}" > "/sys/class/gpio/gpio${TRAY_PIN}/value"
sleep 25
echo "${OFF}" > "/sys/class/gpio/gpio${TRAY_PIN}/value"
