#!/bin/sh -eu

ON='0'
OFF='1'

PLANTS_PIN='23'
echo "${ON}" > "/sys/class/gpio/gpio${PLANTS_PIN}/value"
sleep 1
echo "${OFF}" > "/sys/class/gpio/gpio${PLANTS_PIN}/value"

TRAY_PIN='22'
echo "${ON}" > "/sys/class/gpio/gpio${TRAY_PIN}/value"
sleep 15
echo "${OFF}" > "/sys/class/gpio/gpio${TRAY_PIN}/value"
